title: Portfolio - Tyler Groat
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal portfolio site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tylergroat.github.io" # the base hostname & protocol for your site

# Theme settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if not already present

# Optional settings
show_downloads: true
google_analytics: UA-XXXXXXXX-X # replace with your Google Analytics tracking ID if you have one